[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"


[project]
name = "jaxml"
description = ""
authors = [{name = "Honglu Fan"}]
readme = "README.md"
requires-python = ">=3.10"
version = "0.0.0"
dependencies = [
    "jax==0.5.3",
    "jaxlib==0.5.3",
    "flax==0.10.5",
    "jax-tqdm==0.2.2",
]

[project.optional-dependencies]
tpu = [
    "jax==0.5.3",
    "jaxlib==0.5.3",
    "libtpu @ https://storage.googleapis.com/libtpu-nightly-releases/wheels/libtpu/libtpu-0.0.13.dev20250405+nightly-py3-none-manylinux_2_31_x86_64.whl",
]
dev = [
    "pytest==8.3.4",
    "black==24.0.0",
    "isort==5.13.2",
    "flake8==7.1.1",
    "torch==2.4.0",
    "transformers==4.50.3",
]
